config/routes.rb
Rails.application.routes.draw do

  constraints :protocol => "https" do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  end

  resource :cart, :controller => 'cart'
  resources :orders do
    collection do
      post :paypal 
      get :paypal_complete 
    end
  end

  resource :credit_card do
    get  :decision
  end

  resources :shipping_addresses

  post '/logout', :controller => 'sessions', :action => 'destroy', :as => 'logout'
  get '/login', :controller => 'sessions', :action => 'new', :as => 'login'
  post '/register', :controller => 'users', :action => 'create', :as => 'register'
  get '/signup', :controller => 'users', :action => 'new', :as => 'signup'
  get '/activate/:activation_code', :controller => 'users', :action => 'activate', :activation_code => nil, :as => 'activate'
  resources :users, :member => { :suspend => :put, :unsuspend => :put, :purge => :delete }
  post '/reset_password', :controller => 'users', :action => :reset_password, :as => 'reset_password'
  get '/change_password', :controller => 'users', :action => :change_password, :as => 'change_password'
  post '/search/post', :controller => 'search', :action => 'post', :via => 'post', :as => 'search_post'
  get '/search/:id', :controller => 'search', :action => 'show', :via => 'get', :as => 'search'
  get '/categories/:id', :controller => 'categories', :action => 'index', :as => 'categories'
  get '/manufacturers/:id', :controller => 'manufacturers', :action => 'show'
  get '/categories/sub/:id', :controller => 'categories', :action => 'sub', :as => 'categories_sub'
  get '/new', :controller => 'products', :action => 'new', :as => 'new'
  get '/featured', :controller => 'products', :action => 'featured', :as => 'featured'
  get '/top_sellers', :controller => 'products', :action => 'top_sellers', :as => 'top_sellers'
  get '/recommended', :controller => 'products', :action => 'recommended', :as => 'recommended'
  get '/about', :controller => 'about', :action => 'index'
  get '/contact', :controller => 'about', :action => 'contact'
  get '/policy', :controller => 'about', :action => 'policies'
  get '/fb_coupon', :controller => 'about', :action => 'facebook_coupon'

  resource :session

  get 'products/feed.:format', :controller => 'products', :action => 'feed'
  resources :products

  namespace :admin do
    resources :categories
    controller :categories do
      get 'categories(/:action(/:id(.:format)))'
    end
    resources :products
    controller :products do
      get 'products(/:action(/:id(.:format)))'
    end
  end

  root :to => "products#index"
end

app/models/checkout.rb
#require 'active_shipping'
#include ActiveMerchant::Shipping

class Checkout

  attr_accessor :shipping_cost, :tax, :total, :subtotal

  WEST = ["Washington", "Oregon", "California", "Idaho", "Nevada", "Montana", "Wyoming", "Utah", "Arizona", "Colorado", "New Mexico"]
  CENTRAL = ["North Dakota", "South Dakota", "Nebraska", "Kansas", "Oklahoma", "Texas", "Minnesota", "Iowa", "Missouri", "Arkansas", "Louisiana", "Wisconsin", "Illinois", "Michigan", "Indiana", "Ohio"]
  EAST = [ "Kentucky", "Tennessee", "Mississippi", "Alabama", "West Virginia", "Virginia", "North Carolina", "South Carolina", "Georgia", "Florida", "Maine", "New Hampshire", "Vermont",  "Massachusetts", "New York", "Pennsylvania", "Maryland", "Rhode Island", "Connecticut", "New Jersey", "Delaware"]

  def initialize(user, session_id=nil, shipping_address=nil)
    if user.nil?
      if shipping_address.nil?
        @shipping_cost = 0
        @subtotal = 0 
        @cart = Cart.where(:session_id => session_id.to_s).first
        if @cart
          @cart.products.each do |product|
            @subtotal += product.price
          end
        else
          @cart = @cart.new(:session_id => session_id.to_s)
          @cart.save
        end
        @tax = 0
        @total = @subtotal + @shipping_cost + @tax
      else
        @cart = Cart.where(:session_id => session_id).first
        @address = shipping_address
        calculate_shipping_subtotal
        calculate_tax
        @total = @subtotal + @shipping_cost + @tax
      end
    else
      @address = user.shipping_address
      if shipping_address.nil? and @address.nil?
        @shipping_cost = 0
        @subtotal = 0 
        @cart = user.cart
        @subtotal = 0
        if @cart
          @cart.products.each do |product|
            @subtotal += product.price
          end
        end
        @tax = 0
        @total = @subtotal + @shipping_cost + @tax
      else
        @user = user
        @cart = user.cart
        calculate_shipping_subtotal
        calculate_tax
        @total = @subtotal + @shipping_cost + @tax
      end
    end
  end

private
  def calculate_shipping_subtotal
    total_weight = 0
    @subtotal = 0.0
    total_ship_cost = 0.0
    @shipping_cost = 0 and return if @cart.nil?
    @shipping_cost = 0 and return if @cart.products.nil?
    products = @cart.products
=begin
    destination = Location.new( :country => 'US',
                            :state => STATE_CODES[@address.state.upcase],
                            :city => @address.city,
                            :postal_code => @address.zip)
=end
    products.each do |product|
      @subtotal += product.price
      unless @address.nil?
      #http://github.com/Shopify/active_shipping
      #try this instead
      sender_zip = '97367'
      if product.ds_vendor.class == DandhProduct
        sender_zip = '17101' #harrisburg PA
        if EAST.include?(@address.state)
          sender_zip = '93650' #fresno ca
        end
      end
      #puts 'sender zip is ' + sender_zip
        #ups = Shipping::UPS.new(:city => @address.city, :state => @address.state, :zip => @address.zip, :sender_zip => sender_zip, :weight => product.weight, :ups_license_number => 'F0F0F0F0F0F0F0', :ups_user => 'thedude', :ups_password => 'whiterussian',  :service_type => '3day', :packaging_type => 'your_packaging')
        #total_ship_cost += #ups.price
=begin
        origin = Location.new(      :country => 'US',
                            #:state => 'CA',
                            #:city => 'Beverly Hills',
                            :zip => sender_zip)
       packages = [
                        Package.new(  (product.weight * 16),                 # 7.5 lbs, times 16 oz/lb.
                                      #[15, 10, 4.5],              # 15x10x4.5 inches
                                      [],              # 15x10x4.5 inches
                                      :units => :imperial)        # not grams, not centimetres
        ]

=end

        #ups = UPS.new(:login => 'thedude', :password => 'whiterussian', :key => '0404040404040404')
        #response = ups.find_rates(origin, destination, packages)
        #ups_rates = response.rates.sort_by(&:price).collect {|rate| [rate.service_name, rate.price]}
        #total_ship_cost += (ups_rates.first[1] / 100) + 5
      else
        total_ship_cost = 0
      end
    end
    @shipping_cost = total_ship_cost
  end

  def calculate_tax
    @tax = 0
    unless @address.nil?
      return unless @address.respond_to?(:state)
      if @address.state == 'California' or @address.state == 'CA'  
        @tax = (@subtotal + @shipping_cost) * 0.0825 
      end
    end
  end
  STATE_CODES = {
    'ALABAMA' => 'AL',
    'ALASKA' => 'AK',
    'AMERICAN SAMOA' => 'AS',
    'ARIZONA' => 'AZ',
    'ARKANSAS' => 'AR',
    'CALIFORNIA' => 'CA',
    'COLORADO' => 'CO',
    'CONNECTICUT' => 'CT',
    'DELAWARE' => 'DE',
    'Washington  D.C.' => 'DC',
    'FEDERATED STATES OF MICRONESIA' => 'FM',
    'FLORIDA' => 'FL',
    'GEORGIA' => 'GA',
    'GUAM' => 'GU',
    'HAWAII'  => 'HI',
    'IDAHO' => 'ID',
    'ILLINOIS' => 'IL',
    'INDIANA' => 'IN',
    'IOWA' => 'IA',
    'KANSAS' => 'KS',
    'KENTUCKY' => 'KY',
    'LOUISIANA' => 'LA',
    'MAINE' => 'ME',
    'MARSHALL ISLANDS' => 'MH',
    'MARYLAND' => 'MD', 
    'MASSACHUSETTS' => 'MA',
    'MICHIGAN' => 'MI',
    'MINNESOTA' => 'MN',
    'MISSISSIPPI' => 'MS',
    'MISSOURI' => 'MO',
    'MONTANA' => 'MT',
    'NEBRASKA' => 'NE',
    'NEVADA' => 'NV',
    'NEW HAMPSHIRE'  => 'NH',
    'NEW JERSEY'  => 'NJ',
    'NEW MEXICO' => 'NM',
    'NEW YORK' => 'NY',
    'NORTH CAROLINA' => 'NC',
    'NORTH DAKOTA' => 'ND',
    'NORTHERN MARIANA ISLANDS' => 'MP',
    'OHIO'  => 'OH',
    'OKLAHOMA' => 'OK',
    'OREGON'  => 'OR',
    'PALAU' => 'PW',
    'PENNSYLVANIA' => 'PA',
    'PUERTO RICO' => 'PR',
    'RHODE ISLAND' => 'RI',
    'SOUTH CAROLINA' => 'SC',
    'SOUTH DAKOTA' => 'SD',
    'TENNESSEE' => 'TN',
    'TEXAS' => 'TX',
    'UTAH' => 'UT',
    'VERMONT' => 'VT',
    'VIRGIN ISLANDS' => 'VI',
    'VIRGINIA' => 'VA',
    'WASHINGTON' => 'WA',
    'WEST VIRGINIA' => 'WV',
    'WISCONSIN' => 'WI',
    'WYOMING' => 'WY'
    }

end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  before_action :login_required
  #ssl_required :new, :select_address

  def select_address
    if params[:shipping_address].nil? or params[:shipping_address][:id].nil? or params[:shipping_address][:id].empty? 
      flash[:notice] = 'Please select a shipping address to ship to.'
      redirect_to :controller => :shipping_addresses, :action => :index
      return
    end
    @shipping_address = ShippingAddress.find(params[:shipping_address][:id])
    @shipping_address.set_default!
    redirect_to :action => :new
  end

  def new
    redirect_to '/session/new' and return if current_user.nil? 
    redirect_to '/shipping_addresses/new' and return if current_user.shipping_address.nil? 
    redirect_to '/credit_cards/decision_prompt' and return if session[:payment_method].blank? 
    redirect_to '/credit_cards/new' and return if session[:payment_method] == 'card' and current_user.credit_card.nil?
    redirect_to '/credit_cards/edit' and return if session[:payment_method] == 'card' and not current_user.credit_card.has_billing_details?
    @cart = current_user.cart
    @products = @cart.products
    @shipping_address = current_user.shipping_address
    @credit_card = current_user.credit_card
    @checkout = Checkout.new(current_user)
  end

end

app/views/checkout/new.html.erb
<% content_for :page_stylesheet do -%>
  <%= stylesheet_link_tag 'cart' %>
<% end %>
<div class="section">CONFIRM YOUR ORDER</div>
<% if session[:payment_method] == 'card' %>
  <h3>By clicking checkout you agree to the policies page, and your credit card will be charged for the following products</h3>
<% else %>
  <h3>By clicking checkout you agree with the policies page, and you will be redirected to the paypal website</h3>
<% end %>
<table id="order_details">
  <tr>
    <td><b>Shipping Address</b></td>
    <td><b>Payment Info</b></td>
  </tr>
  <tr>
    <td>
      <% if session[:payment_method] == 'card' %>
        Currently we can only ship to <br/> your billing address.<br/><br/>
        <%= @credit_card.first_name %> <%= @credit_card.last_name %><br/>
        <%= @credit_card.address %><br/>
        <%= @credit_card.city %>, <%= @credit_card.state %> <%= @credit_card.zip %><br/>
        <%= link_to 'Edit shipping details', edit_credit_card_path %>
      <% else %>
      <%= @shipping_address.first_name %> <%= @shipping_address.last_name %><br/>
        <%= @shipping_address.address1 %><br/>
        <% unless @shipping_address.address2.empty? %> <%= @shipping_address.address2 %><br/> <% end %>
        <%= @shipping_address.city %>, <%= @shipping_address.state %> <%= @shipping_address.zip %><br/>
        <%= link_to 'Edit shipping details', shipping_addresses_path %>
      <% end %>
    </td>
    <td>
      <% if session[:payment_method] == 'card' %>
        <%= @credit_card.first_name %> <%= @credit_card.last_name %><br/>
        <%= @credit_card.display_number %><br/>
        <%= @credit_card.month%>/<%= @credit_card.year %><br/>
        <%= @credit_card.verification_value %><br/>
        <%= link_to 'Edit Credit Card Details', edit_credit_card_path %><br/>
        <%= link_to 'Change payment method', :controller => 'credit_cards', :action => :decision_prompt %>
      <% else %>
        Paypal Express Checkout<br/>
        <img src="https://www.paypal.com/en_US/i/logo/PayPal_mark_37x23.gif" align="left" style="margin-right:7px;"><span style="font-size:11px; font-family: Arial, Verdana;">The safer, easier way to pay.</span><br/><br/>
        <%= link_to 'Edit', :controller => 'credit_cards', :action => :decision_prompt %>
      <% end %>
    </td>
  </tr>
</table>
<br/>
<br/>
<table id="checkout">
  <tr>
    <th>Product</th>
    <th>Description</th>
    <th>Price</th>
  </tr>

<% @products.each do |product| 
%>
  <tr class="<%=cycle('odd', 'even') %>">
    <td class="item_pic"><%= link_to(image_tag(product.image(75), :width => 75, :height => 75), product) %></td>
    <td><%= link_to(truncate(product.title, :length => 49), product) %></td>
    <td><%= number_to_currency(product.price) %></td>
  </tr>
<% end %>
<% if @checkout %>
  <tr class="even">
    <td>&nbsp;</td>
    <td>Subtotal:</td>
    <td><%= number_to_currency(@checkout.subtotal) %></td>
  </tr>
  <tr class="even">
    <td>&nbsp;</td>
    <td>Shipping:</td>
    <td><%= number_to_currency(@checkout.shipping_cost) %></td>
  </tr>
  <tr class="even">
    <td>&nbsp;</td>
    <td>Tax:</td>
    <td><%= number_to_currency(@checkout.tax) %></td>
  </tr>
  <tr class="even">
    <td>&nbsp;</td>
    <td>Total:</td>
    <td><b><%= number_to_currency(@checkout.total) %></b></td>
  </tr>
  <tr class="even">
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td><br/>
      <% if session[:payment_method] == 'card' %>
        <%= form_for 'order', :url => orders_path do |f| %>
          <%= submit_tag 'submit', :src => '/images/button_checkout.jpg', :type => :image %> 
        <% end %>
      <% else %>
        <%= form_for 'order', :url => paypal_orders_path do |f| %>
          <%= submit_tag 'submit', :src => 'https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif', :type => :image %> 
        <% end %>
      <% end %>
    </td>
  </tr>
  <% end %>
</table>