config/routes.rb
Rails.application.routes.draw do

  constraints :protocol => "https" do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  end

  resource :cart, :controller => 'cart'
  resources :orders do
    collection do
      post :paypal 
      get :paypal_complete 
    end
  end

  resource :credit_card do
    get  :decision
  end

  resources :shipping_addresses

  post '/logout', :controller => 'sessions', :action => 'destroy', :as => 'logout'
  get '/login', :controller => 'sessions', :action => 'new', :as => 'login'
  post '/register', :controller => 'users', :action => 'create', :as => 'register'
  get '/signup', :controller => 'users', :action => 'new', :as => 'signup'
  get '/activate/:activation_code', :controller => 'users', :action => 'activate', :activation_code => nil, :as => 'activate'
  resources :users, :member => { :suspend => :put, :unsuspend => :put, :purge => :delete }
  post '/reset_password', :controller => 'users', :action => :reset_password, :as => 'reset_password'
  get '/change_password', :controller => 'users', :action => :change_password, :as => 'change_password'
  post '/search/post', :controller => 'search', :action => 'post', :via => 'post', :as => 'search_post'
  get '/search/:id', :controller => 'search', :action => 'show', :via => 'get', :as => 'search'
  get '/categories/:id', :controller => 'categories', :action => 'index', :as => 'categories'
  get '/manufacturers/:id', :controller => 'manufacturers', :action => 'show'
  get '/categories/sub/:id', :controller => 'categories', :action => 'sub', :as => 'categories_sub'
  get '/new', :controller => 'products', :action => 'new', :as => 'new'
  get '/featured', :controller => 'products', :action => 'featured', :as => 'featured'
  get '/top_sellers', :controller => 'products', :action => 'top_sellers', :as => 'top_sellers'
  get '/recommended', :controller => 'products', :action => 'recommended', :as => 'recommended'
  get '/about', :controller => 'about', :action => 'index'
  get '/contact', :controller => 'about', :action => 'contact'
  get '/policy', :controller => 'about', :action => 'policies'
  get '/fb_coupon', :controller => 'about', :action => 'facebook_coupon'

  resource :session

  get 'products/feed.:format', :controller => 'products', :action => 'feed'
  resources :products

  namespace :admin do
    resources :categories
    controller :categories do
      get 'categories(/:action(/:id(.:format)))'
    end
    resources :products
    controller :products do
      get 'products(/:action(/:id(.:format)))'
    end
  end

  root :to => "products#index"
end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :address, :city, :state, :zip, :number, :first_name, :last_name, :month, :year, :phone_number #, :verification_value
  validates_length_of :number, :within => 13..16,  :too_long => "your card number is too long", :too_short => "your card number is too short"
  #validates_numericality_of :year, :verification_value
  validates_numericality_of :month, :greater_than => 0, :less_than => 13
  validate :check_vv, :ensure_valid_date, :valid_card?

  before_save :kill_dcvv
  #before_save :check_vv

  def has_billing_details?
    if self.address.length > 4 and self.city.length > 2 and self.zip.length > 4 and self.state.length > 1
      return true
    else
      return false
    end
  end

  def kill_dcvv
    if self.number[0].chr == '6'
      self.verification_value = ''
    end
  end

  def check_vv
    if self.number[0] == 6
      self.verification_value = ''
    else
      if self.verification_value.length > 0 or self.verification_value.gsub(/[0-9]+/, '') == '' 
        return false
      else
        self.errors.add(:base, 'Please enter a valid verification value.')
      end
    end
    return true
  end

  def ensure_valid_date
    today = Date.today
    card_date = Date.new(self.year, self.month, 1)
    unless card_date > today
      self.errors.add(:base, 'Please make sure your credit card has not already expired.')
    end
  end

  def valid_card?
    #used to do credit card auth - but now we dont care
    return true
    if Rails.env.test? == 'test' or Rails.env.development? == 'development'
      test = true
    else
      test = false
    end
    ActiveMerchant::Billing::Base.mode = :production
    credit_card = create_active_merchant_card
    unless credit_card.valid?
      errors.add(:base, 'It appears this is not a valid credit card. Please double check the number and try again.')
      return 
    end
    gateway = ActiveMerchant::Billing::AuthorizeNetGateway.new(
          :login    => '9vLbG97Lfg8',
          :password => '98g9574fkLeBmT8j',
          :test => test
        )
    billing_address = { :address => self.address, :city => self.city, :state => self.state, :zip => self.zip, :country => 'US', :phone => self.phone_number}
    response = gateway.authorize(rand(100) + 1, credit_card, {:billing_address => billing_address})
    ##used to do the following to validate address
    @ups = Shipping::UPS.new(:city => self.city, :state => self.state, :zip => self.zip)
    unless @ups.valid_address?
      errors.add(:base, 'You seem to have an invalid address. Please ensure you have the proper city, state, and zip.')
      return false
    end
    ######
    #avs_success = false
    #puts 'street match is ' + response.avs_result[:street_match]
    #if response.avs_result['street_match'] == 'Y'
    #  avs_success = true
    #end
    #if avs_success and response.success?
    #be nice if the avs success code worked - but it doesn't
    if response.success?
      return true
    else 
      errors.add(:base, 'We could not authorize your credit card. Please verify the details, and the billing address are correct, and please verify you are using Visa, MasterCard, Discover, Diners Club, or JCB.')
      return false
    end
  end

  def display_number
    credit_card = create_active_merchant_card
    credit_card.display_number
  end

  def create_active_merchant_card
    #cvv = self.verification_value
    #if self.verification_value == ''
    #  cvv = '123'
    #end
    credit_card = ActiveMerchant::Billing::CreditCard.new(
                  :first_name         => self.first_name,
                  :last_name          => self.last_name,
                  :number             => self.number,
                  :month              => self.month,
                  :year               => self.year,
                  :verification_value => self.verification_value
                )
  end
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  before_filter :login_required, :except => [:decision, :new, :create]
  ssl_required :show, :new, :edit, :create, :update 

  # GET /credit_cards/1
  # GET /credit_cards/1.xml
  def show
    @credit_card = Cache.get 'user_' + current_user.id.to_s + '_creditcard'
    unless @credit_card
      @credit_card = current_user.credit_card
      Cache.put 'user_' + current_user.id.to_s + '_creditcard', @credit_card
    end
    redirect_to :action => :edit and return unless @credit_card.valid? 
    @cart = current_user.cart
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @credit_card }
    end
  end

  def decision_prompt
  end

  def decision
    @method = params[:payment_method]
    if @method.nil?
      flash[:notice] = "Please select a payment method"
      redirect_to :action => :decision_prompt and return
    end
    if @method[:id] == 'paypal'
      session[:payment_method] = 'paypal'
      if current_user.shipping_address
        redirect_to :controller => :checkout, :action => :new
      else
        redirect_to :controller => :shipping_addresses, :action => :new
      end
    elsif @method[:id] == 'card'
      session[:payment_method] = 'card'
      if current_user.nil? or current_user.credit_card.nil?
        redirect_to :action => :new
      else
        redirect_to :controller => :checkout, :action => :new
      end
    end
  end
  # GET /credit_cards/new
  # GET /credit_cards/new.xml
  def new
    if current_user.nil?
      @user = User.new
    end
    @credit_card = CreditCard.new(:month => Date.today.month, :year => Date.today.year)

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @credit_card }
    end
  end

  # GET /credit_cards/1/edit
  def edit
    @credit_card = current_user.credit_card 
    @cart = current_user.cart
  end

  # POST /credit_cards
  # POST /credit_cards.xml
  def create
    if current_user.nil?
      @user = User.new(params[:user].merge(:password_confirmation => params[:user][:password]))
      if @user.save
        #set current cart and shipping to this new user
        user = User.authenticate(params[:user][:email], params[:user][:password])
        self.current_user = user 
        new_cookie_flag = true #old (params[:remember_me] == "1")
        #handle_remember_cookie! new_cookie_flag
        shipping_address = ShippingAddress.find_by_session_id(request.session_options[:id])
        cart = Cart.find_by_session_id(request.session_options[:id])
        cart.user = current_user
        cart.save
        shipping_address.user = current_user
        shipping_address.save
      else
        @credit_card = CreditCard.new(params[:credit_card])
        render :new
        return
      end
    end
    @credit_card = CreditCard.new(params[:credit_card])
    @credit_card.user = current_user

    respond_to do |format|
      if @credit_card.save
        Cache.put 'user_' + current_user.id.to_s + '_creditcard', @credit_card
        format.html { redirect_to({:action => :new, :controller => :checkout}, :notice => 'Credit card info successfully saved.') }
        format.xml  { render :xml => @credit_card, :status => :created, :location => @credit_card }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @credit_card.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /credit_cards/1
  # PUT /credit_cards/1.xml
  def update
    @credit_card = Cache.get 'user_' + current_user.id.to_s + '_creditcard'
    unless @credit_card
      @credit_card = current_user.credit_card
    end

    respond_to do |format|
      if @credit_card.update_attributes(params[:credit_card].merge(params[:date]))
        Cache.put 'user_' + current_user.id.to_s + '_creditcard', @credit_card.reload
        format.html { redirect_to({:action => :new, :controller => :checkout}, :notice => 'Your credit card was successfully updated.') }
        format.xml  { head :ok }
      else
      	@cart = current_user.cart
        format.html { render :action => "edit" }
        format.xml  { render :xml => @credit_card.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /credit_cards/1
  # DELETE /credit_cards/1.xml
=begin
  def destroy
    @credit_card = CreditCard.find(params[:id])
    @credit_card.destroy

    respond_to do |format|
      format.html { redirect_to(credit_cards_url) }
      format.xml  { head :ok }
    end
  end
=end
end

app/views/credit_cards/decision_prompt.html.erb
<% content_for :page_stylesheet do -%>
  <%= stylesheet_link_tag 'cart' %>
<% end %>
<div class="section">YOUR PAYMENT METHOD</div>
<div id="decision">

  <b>Select your payment method</b>
  <br/>
  <br/>
    <%= form_for(:decision, :url => { :action => :decision, :controller => :credit_cards}) do |f| %>
      <table id="payment_method">
        <tr>
          <td width="1%"><%= radio_button("payment_method", "id", "card") %></td>
          <td>
              <%= image_tag('/images/credit_card_logo.jpg', :width => '133', :height => '28') %>
          </td>
        </tr>

        <tr>
          <td width="1%"><%= radio_button("payment_method", "id", "paypal") %></td>
          <td>
              <img src="https://www.paypal.com/en_US/i/logo/PayPal_mark_37x23.gif" align="left" style="margin-right:7px;"><span style="font-size:11px; font-family: Arial, Verdana;">The safer, easier way to pay.</span>
          </td>
        </tr>

        <tr>
          <td>&nbsp;</td>
          <td><br/><br/><%= f.submit 'Select', :src => '/images/button_submit.jpg', :type => 'image' %> </td>
        </tr>
      </table>
    <% end %>

  <br />

</div>

app/views/credit_cards/edit.html.erb
<div class="section">YOUR CREDIT CARD</div>
<div id="entry-form">
By using a credit card we can only ship to your billing address.

<%= form_for(@credit_card, :url => credit_card_path, :method => :put) do |f| %>
   <% if @credit_card.errors.any? %>
     <% @credit_card.errors.full_messages.each do |msg| %>  
         <%= msg %><br>
       <% end %>  
   <% end %>  

  <p>
    <%= f.label :contact_phone_number %><br />
    <%= f.text_field :phone_number %>
  </p>
  <p>
    <%= f.label :billing_address %><br />
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :billing_city %><br />
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :billing_state %><br />
    <%= f.text_field :state %>
  </p>
  <p>
    <%= f.label :billing_zip %><br />
    <%= f.text_field :zip %>
  </p>
  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :card_number %><br />
    <%= f.text_field :number %>
  </p>
  <p>
    <%= f.label :month %><br />
    <%= select_month(@credit_card.month) %>
  </p>
  <p>
    <%= f.label :year %><br />
    <%= select_year(@credit_card.year, :start_year => Date.today.year, :end_year => Date.today.year + 10) %>
  </p>
  <p>
    <%= f.label :verification_value %><br />
    <%= f.text_field :verification_value %>
  </p>
  <div id="entry-form-submit">
    <p>
      <%= f.submit 'Update', :src => '/images/button_submit.jpg', :type => 'image' %>
    </p>
  </div>
<% end %>

<% if @cart.cart_products.count > 0 %>
<%= link_to 'Back to cart', "/cart/show" %>
<% end %>
</div>

app/views/credit_cards/index.html.erb
<h1>Listing credit_cards</h1>

<table>
  <tr>
    <th>User</th>
    <th>Number</th>
    <th>Month</th>
    <th>Year</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Verification value</th>
  </tr>

<% @credit_cards.each do |credit_card| %>
  <tr>
    <td><%=h credit_card.user_id %></td>
    <td><%=h credit_card.number %></td>
    <td><%=h credit_card.month %></td>
    <td><%=h credit_card.year %></td>
    <td><%=h credit_card.first_name %></td>
    <td><%=h credit_card.last_name %></td>
    <td><%=h credit_card.verification_value %></td>
    <td><%= link_to 'Show', credit_card %></td>
    <td><%= link_to 'Edit', edit_credit_card_path(credit_card) %></td>
    <td><%= link_to 'Destroy', credit_card, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New credit_card', new_credit_card_path %>

app/views/credit_cards/new.html.erb
<% content_for :page_js do-%>
<script type="text/javascript">
  $(document).ready(function(){ 
    if( $('#phone_number').val() == '5305148831') {
      $('#phone_number').val('');
    }
      
    $('.rounded').corners();
    $('#decided').click(function(){
      $('#decision_form').submit();
    });
  });

</script>
<% end %>
<div class="section">PERSONAL INFORMATION</div>
By using a credit card we can only ship to your billing address.
<div id="entry-form">

  <%= form_for :personal_info, :url => credit_card_path do |f| %>
    <% if @user and @user.errors.any? %>
      <% @user.errors.full_messages.each do |msg| %>  
        <%= msg %><br>
      <% end %>  
    <% end %>  
    <% if @credit_card.errors.any? %>
      <% @credit_card.errors.full_messages.each do |msg| %>  
        <%= msg %><br>
      <% end %>  
    <% end %>  

    <% if current_user.nil? %>
    <p>
      <%= f.label :your_email %><br />
      <%= text_field :user, :email %>
    </p>
    <p>
      <%= f.label :choose_a_password %><br />
      <%= password_field :user, :password %>
    </p>
    <% end %>
    <p>
      <%= f.label :contact_phone_number %><br />
      <%= text_field :credit_card, :phone_number, :id => 'phone_number' %>
    </p>
    <p>
      <%= f.label :billing_address %><br />
      <%= text_field :credit_card, :address %>
    </p>
    <p>
      <%= f.label :billing_city %><br />
      <%= text_field :credit_card, :city %>
    </p>
    <p>
      <%= f.label :billing_state %><br />
      <%= text_field :credit_card, :state %>
    </p>
    <p>
      <%= f.label :billing_zip %><br />
      <%= text_field :credit_card, :zip %>
    </p>
    <p>
      <%= f.label :credit_card_first_name %><br />
      <%= text_field :credit_card, :first_name %>
    </p>
    <p>
      <%= f.label :credit_card_last_name %><br />
      <%= text_field :credit_card, :last_name %>
    </p>
    <p>
      <%= f.label :credit_card_number %><br />
      <%= text_field :credit_card, :number %>
    </p>
    <p>
      <%= f.label :month %><br />
      <%= select_month @credit_card.month, :field_name => 'month', :prefix => 'credit_card'  %>
    </p>
    <p>
      <%= f.label :year %><br />
      <%= select_year(@credit_card.year, :start_year => Date.today.year, :end_year => Date.today.year + 10, :field_name => 'year', :prefix => 'credit_card') %>

    </p>
    <p>
      <%= f.label :card_verification_value %><br />
      <%= text_field :credit_card, :verification_value %>
    </p>
    <div id="entry-form-submit">
      <p>
        <%= f.submit 'Create', :type => 'image', :src => '/images/button_submit.jpg' %>
      </p>
    </div>
  <% end %>

  <%= link_to 'Back', :action => :decision_prompt, :controller => :credit_cards %>
</div>

app/views/credit_cards/show.html.erb
<div class="section">YOUR CREDIT CARD</div>
<div class="main-body-content">
<table>
  <tr>
    <td>
      <b>First name:</b>
    </td>
    <td>
      <%=h @credit_card.first_name %>
    </td>
  </tr>
    <td>
      <b>Last name:</b>
    </td>
    <td>
        <%=h @credit_card.last_name %>
    </td>
  </tr>
  <tr>
    <td><b>Card Number:</b></td>
    <td><%=h @credit_card.display_number %></td>
  </tr>
  <tr>
    <td>
      <b>Month / Year:</b>
    </td>
    <td>
      <%=h @credit_card.month %>/ <%=h @credit_card.year %>
    </td>
  </tr>
  <tr>
    <td>
      <b>Verification value:</b>
    </td>
    <td>
      <%=h @credit_card.verification_value %>
    </td>
  </tr>
  <tr>
    <td>
      <%= link_to 'Edit my credit card details', edit_credit_card_path %>
    </td>
    <td>
      <% if @cart.cart_products.count > 0 %>
        <%= link_to image_tag('/images/button_checkout.jpg'), shipping_addresses_path %>
      <% end %>
    </td>
  </tr>
</table>
</div>