config/routes.rb
Rails.application.routes.draw do

  constraints :protocol => "https" do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  end

  resource :cart, :controller => 'cart'
  resources :orders do
    collection do
      post :paypal 
      get :paypal_complete 
    end
  end

  resource :credit_card do
    get  :decision
  end

  resources :shipping_addresses

  post '/logout', :controller => 'sessions', :action => 'destroy', :as => 'logout'
  get '/login', :controller => 'sessions', :action => 'new', :as => 'login'
  post '/register', :controller => 'users', :action => 'create', :as => 'register'
  get '/signup', :controller => 'users', :action => 'new', :as => 'signup'
  get '/activate/:activation_code', :controller => 'users', :action => 'activate', :activation_code => nil, :as => 'activate'
  resources :users, :member => { :suspend => :put, :unsuspend => :put, :purge => :delete }
  post '/reset_password', :controller => 'users', :action => :reset_password, :as => 'reset_password'
  get '/change_password', :controller => 'users', :action => :change_password, :as => 'change_password'
  post '/search/post', :controller => 'search', :action => 'post', :via => 'post', :as => 'search_post'
  get '/search/:id', :controller => 'search', :action => 'show', :via => 'get', :as => 'search'
  get '/categories/:id', :controller => 'categories', :action => 'index', :as => 'categories'
  get '/manufacturers/:id', :controller => 'manufacturers', :action => 'show'
  get '/categories/sub/:id', :controller => 'categories', :action => 'sub', :as => 'categories_sub'
  get '/new', :controller => 'products', :action => 'new', :as => 'new'
  get '/featured', :controller => 'products', :action => 'featured', :as => 'featured'
  get '/top_sellers', :controller => 'products', :action => 'top_sellers', :as => 'top_sellers'
  get '/recommended', :controller => 'products', :action => 'recommended', :as => 'recommended'
  get '/about', :controller => 'about', :action => 'index'
  get '/contact', :controller => 'about', :action => 'contact'
  get '/policy', :controller => 'about', :action => 'policies'
  get '/fb_coupon', :controller => 'about', :action => 'facebook_coupon'

  resource :session

  get 'products/feed.:format', :controller => 'products', :action => 'feed'
  resources :products

  namespace :admin do
    resources :categories
    controller :categories do
      get 'categories(/:action(/:id(.:format)))'
    end
    resources :products
    controller :products do
      get 'products(/:action(/:id(.:format)))'
    end
  end

  root :to => "products#index"
end

app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_and_belongs_to_many :roles
  has_one :cart, :dependent => :destroy
  has_one :credit_card, :dependent => :destroy
  has_many :shipping_addresses, :dependent => :destroy
  has_one :shipping_address, -> { :current_default => true}
  has_many :orders

  before_create :generate_activation_code

  validates_presence_of     :email
  validates_length_of       :email,    :within => 6..100 #r@a.wk
  validates_uniqueness_of   :email
  #validates_format_of       :email,    :with => Authentication.email_regex, :message => Authentication.bad_email_message

   

  # HACK HACK HACK -- how to do attr_accessible from here?
  # prevents a user from submitting a crafted form that bypasses activation
  # anything else you want your user to change should be added here.
  attr_accessor :email, :password, :password_confirmation



  def has_role?(type)
    rs = self.roles
    rs.each do |r|
      return true if r.name == type
    end
    return false
  end

  # Authenticates a user by their email and unencrypted password.  Returns the user or nil.
  #
  # uff.  this is really an authorization, not authentication routine.  
  # We really need a Dispatch Chain here or something.
  # This will also let us return a human error message.
  #
  def self.authenticate(email, password)
    return nil if email.blank? || password.blank?
    #old u = find_by_login(login.downcase) # need to get the salt
    u = find_by_email(email.downcase) # need to get the salt
    #should use this line - but for now
    #u && u.authenticated?(password) && u.activation_code == nil ? u : nil
    u && u.authenticated?(password) ? u : nil
  end

  def activate!
    self.activation_code = nil
    self.save
  end

  def email=(value)
    write_attribute :email, (value ? value.downcase : nil)
  end

  def generate_activation_code
    self.activation_code = Digest::SHA1.hexdigest( Time.now.to_s.split(//).sort_by {rand}.join)
  end
  
  def reset_password!
    size = 6
    chars = (('a'..'z').to_a + ('0'..'9').to_a) - %w(i o 0 1 l 0)
    self.password = (1..size).collect{|a| chars[rand(chars.size)] }.join
    self.password_confirmation = self.password
    UserMailer.deliver_new_password(self) 
    self.save
  end

  def remember_token?
    (!remember_token.blank?) && 
      remember_token_expires_at && (Time.now.utc < remember_token_expires_at.utc)
  end

  # These create and unset the fields required for remembering users between browser closes
  def remember_me
    remember_me_for 2.weeks
  end

  def remember_me_for(time)
    remember_me_until time.from_now.utc
  end

  def remember_me_until(time)
    self.remember_token_expires_at = time
    self.remember_token            = self.class.make_token
    return false
  end

  # refresh token (keeping same expires_at) if it exists
  def refresh_token
    if remember_token?
      self.remember_token = self.class.make_token 
      return false
    end
  end

  # 
  # Deletes the server-side record of the authentication token.  The
  # client-side (browser cookie) and server-side (this remember_token) must
  # always be deleted together.
  #
  def forget_me
    self.remember_token_expires_at = nil
    self.remember_token            = nil
    save(false)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_required, :only => [ :change_password, :index ]  
  #before_action :ssl_required, :only => [ :new, :create, :reset_password, :change_password]

  def index
  end

  # render new.rhtml
  def new
    @user = User.new
  end
 
  def create
    logout_keeping_session!
    @user = User.new(params[:user])
    success = @user && @user.save
    if success && @user.errors.empty?
            # Protects against session fixation attacks, causes request forgery
      # protection if visitor resubmits an earlier form using back
      # button. Uncomment if you understand the tradeoffs.
      # reset session
      self.current_user = @user # !! now logged in
      @cart = Cart.find_by_session_id(request.session_options[:id])
      if @cart
        @cart.user = @user
        @cart.save
      end
      redirect_back_or_default('/cart/show')
      flash[:notice] = "Thanks for signing up!  We're sending you an email with your activation code."
    else
      flash[:error]  = "We couldn't set up that account, sorry.  Please try again, or contact us."
      render :action => 'new'
    end
  end

  def activate
    @user = User.find_by_activation_code(params[:activation_code])
    if @user 
      @user.activate!
      flash[:notice] = "You can now login to your account."
    else
      flash[:notice] = "We couldn't find that activation code. Perhaps your account is already activated? Try logging in."
    end 
    redirect_to login_path
  end

  def reset_password
    return unless request.post?
    @user = User.find_by_email(params[:email])
    if @user
      @user.reset_password!
      flash.now[:notice] = 'Your password has been reset. Please check your email for your new password.'
    else
      flash.now[:notice] = 'We could not find your email address. Please sign up if you have not already.'
    end
  end

  def change_password
    return unless request.post?
    if params[:user][:password].blank?
      flash.now[:notice] = 'Please do not enter a blank password.'
      return
    end
    current_user.password = params[:user][:password]
    current_user.password_confirmation = params[:user][:password_confirmation]
    if current_user.save
      flash.now[:notice] = 'Your password has been updated.'
    else
      flash.now[:error] = 'Please check the errors below.'
    end
  end
end

app/views/users/_user_bar.html.erb
<% if logged_in? -%>
  <div id="user-bar-greeting">Logged in as <%= link_to_current_user :content_method => :login %></div>
  <div id="user-bar-action"  >(<%= link_to "Log out", logout_path, { :title => "Log out" }    %>)</div>
<% else -%>
  <div id="user-bar-greeting"><%= link_to_login_with_IP 'Not logged in', :style => 'border: none;' %></div>
  <div id="user-bar-action"  ><%= link_to "Log in",  login_path,  { :title => "Log in" } %> /
                               <%= link_to "Sign up", signup_path, { :title => "Create an account" } %></div>
<% end -%>

app/views/users/change_password.html.erb
<div class="section">YOUR NEW PASSWORD</div>
<div id="entry-form">
  <% current_user.password = current_user.password_confirmation = nil %> 

  <% if current_user.errors.any? %>
    <% current_user.errors.full_messages.each do |msg| %>
      <%= msg %><br>
    <% end %>
  <% end %> 
  <%= form_for :user, :url => change_password_path do |f| -%>

  <p><%= f.label :password %><br/>
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation, 'Confirm Password' %><br/>
  <%= f.password_field :password_confirmation %></p>

  <div id="entry-form-submit">
    <%= submit_tag 'Change it', :src => '/images/button_submit.jpg', :type => 'image' %>
  </div>
  <% end -%>
  <br/>
  <br/>
  <%= link_to 'Back to your account page', users_path %>
</div>

app/views/users/index.html.erb
<div class="section">YOUR ACCOUNT</div>
<br/>
<br/>
<br/>
<div id="entry-form">
  You are logged in as <%= current_user.email %> <% if current_user.has_role?('admin') %> (You are an admin) <% end %>
  <p>
  <% if current_user.has_role?('admin') %> 
    <%= link_to 'Change category tree', admin_categories_path %>
  <% end %>
  </p>
  <p>
  <%= link_to 'Change your password', change_password_path %>
  </p>
  <% if current_user.credit_card %>
    <p>
      <%= link_to 'Update your credit card details', edit_credit_card_path %>
    </p>
  <% end %>


  <p>
  <%= link_to 'Logout', logout_path %>
  </p>
</div>

app/views/users/new.html.erb
<div class="section">SIGN UP AS A NEW USER</div>
<div id="entry-form">
  <% @user.password = @user.password_confirmation = nil %>

  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <%= msg %><br>
    <% end %>
  <% end %> 
  <%= form_for :user, :url => users_path do |f| -%>

  <p><%= f.label :email %><br/>
  <%= f.text_field :email %></p>

  <p><%= f.label :password %><br/>
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation, 'Confirm Password' %><br/>
  <%= f.password_field :password_confirmation %></p>

  <div id="entry-form-submit">
    <p><%= submit_tag 'Sign up', :src => '/images/button_submit.jpg', :type => 'image' %></p>
  </div>
  <% end -%>
<p><%= link_to 'back to login', login_path %></p>
</div>

app/views/users/reset_password.html.erb
<h1>Forgot your password?</h1>

<% form_tag reset_password_path do -%>
<p><%= label_tag 'email' %><br />
<%= text_field_tag 'email', @email %></p>

<p><%= submit_tag 'Request' %></p>
<p><%= link_to "I'm new, sign me up", new_user_path %></p>
<% end -%>