config/routes.rb
Rails.application.routes.draw do

  constraints :protocol => "https" do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  end

  resource :cart, :controller => 'cart'
  resources :orders do
    collection do
      post :paypal 
      get :paypal_complete 
    end
  end

  resource :credit_card do
    get  :decision
  end

  resources :shipping_addresses

  post '/logout', :controller => 'sessions', :action => 'destroy', :as => 'logout'
  get '/login', :controller => 'sessions', :action => 'new', :as => 'login'
  post '/register', :controller => 'users', :action => 'create', :as => 'register'
  get '/signup', :controller => 'users', :action => 'new', :as => 'signup'
  get '/activate/:activation_code', :controller => 'users', :action => 'activate', :activation_code => nil, :as => 'activate'
  resources :users, :member => { :suspend => :put, :unsuspend => :put, :purge => :delete }
  post '/reset_password', :controller => 'users', :action => :reset_password, :as => 'reset_password'
  get '/change_password', :controller => 'users', :action => :change_password, :as => 'change_password'
  post '/search/post', :controller => 'search', :action => 'post', :via => 'post', :as => 'search_post'
  get '/search/:id', :controller => 'search', :action => 'show', :via => 'get', :as => 'search'
  get '/categories/:id', :controller => 'categories', :action => 'index', :as => 'categories'
  get '/manufacturers/:id', :controller => 'manufacturers', :action => 'show'
  get '/categories/sub/:id', :controller => 'categories', :action => 'sub', :as => 'categories_sub'
  get '/new', :controller => 'products', :action => 'new', :as => 'new'
  get '/featured', :controller => 'products', :action => 'featured', :as => 'featured'
  get '/top_sellers', :controller => 'products', :action => 'top_sellers', :as => 'top_sellers'
  get '/recommended', :controller => 'products', :action => 'recommended', :as => 'recommended'
  get '/about', :controller => 'about', :action => 'index'
  get '/contact', :controller => 'about', :action => 'contact'
  get '/policy', :controller => 'about', :action => 'policies'
  get '/fb_coupon', :controller => 'about', :action => 'facebook_coupon'

  resource :session

  get 'products/feed.:format', :controller => 'products', :action => 'feed'
  resources :products

  namespace :admin do
    resources :categories
    controller :categories do
      get 'categories(/:action(/:id(.:format)))'
    end
    resources :products
    controller :products do
      get 'products(/:action(/:id(.:format)))'
    end
  end

  root :to => "products#index"
end

app/models/product.rb
class Product < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 24
  belongs_to :ds_vendor, :polymorphic => true
  belongs_to :category
  has_many :product_images, -> { order('width desc') }
  has_one :product_image, -> { where( :hero => true ) }

#  validates_uniqueness_of :title
  DS_VENDORS = [ 'Dsdi' ]
  BUCKET = 'buymeyo_prod'

  before_save :sanitize_manufacturer


  def sanitize_manufacturer
    self.manufacturer = Product.sanitize(self.manufacturer)
  end

  def self.sanitize(name)
    name = name.gsub(/[^0-9A-Za-z]|[ ]+/, ' ')
    name = name.gsub(/ +/, ' ')
    return name
  end

  def not_na?
    case self.availability
      when 'Yes'
        return true
      when 'No'
        return true
      else
        return false
    end
  end

  def display_availability
    case self.availability
      when 'Yes'
        return 'Yes'
      when 'No'
        return 'No'
      else
        return 'NA'
    end
  end

  def image_width
    width = 300
    i = ProductImage.find(:first, :conditions => {:product_id => self.id, :thumbnail => false})
    width = i.width unless i.nil?
    return width
  end

  def image(size = nil)
    if self.ds_vendor_type == 'DandhProduct' or self.ds_vendor_type == 'DsdiProduct'
      case size
        when nil
          location = 'https://s3.amazonaws.com/' + BUCKET + '/' + self.title.parameterize.to_s + '.jpg'
        when 75
          location = 'https://s3.amazonaws.com/' + BUCKET + '/' + self.title.parameterize.to_s + '.jpg'
        when 150
          location = 'https://s3.amazonaws.com/' + BUCKET + '/' + self.title.parameterize.to_s + '-x150.jpg'
        when 300
          location = 'https://s3.amazonaws.com/' + BUCKET + '/' + self.title.parameterize.to_s + '.jpg'
        end
      return location
    end
    i = nil
    case size
      when nil
        i = self.product_images.detect { |pi| pi.thumbnail == false }
      when 75
        i = self.product_images.detect { |pi| pi.width == '75'}
      when 150
        i = self.product_images.detect { |pi| pi.width == '150'}
      when 300
        i = self.product_images.detect { |pi| pi.width == '300'}
    end
    if i.nil?
        i = self.product_images.first #find(:first, :conditions => {:order => 'width desc'})
    end
    if i.nil?
      case size
        when nil
          return 'no_image.jpg'
        when 75
          return 'no_image-x75.jpg'
        when 150
          return 'no_image-x150.jpg'
        when 300
          return 'no_image.jpg'
      end
    else
      i.public_filename
    end
  end

  def imagex75 
    location = 'https://s3.amazonaws.com/' + BUCKET + '/' + self.title.parameterize.to_s + '-x75.jpg'
  end

  def imagex150 
    location = 'https://s3.amazonaws.com/' + BUCKET + '/' + self.title.parameterize.to_s + '-x150.jpg'
  end

  def old_image
    location = 'https://s3.amazonaws.com/' + BUCKET + '/' + self.title.parameterize.to_s + '.jpg'
  end

  def to_param
    #slug
    link = title.parameterize
    #do this after images are in DB
    #size = link.size
    #if size > 80
    #  size = 80
    #end
    #link = link[0, size - 1]
    "#{id}-#{link}"
  end

  FIVEHUNDRED = ['purchase a new computer', 'buy a new hd tv', 'buy a used car', 'purchase a set of new tires' ]
  THREEHUNDRED = ['buy a new tv', 'buy a new computer monitor', 'buy a really nice external hard drive']
  TWOHUNDRED = ['take your family out to dinner', 'take a few friends to sushi', 'buy an external hard drive for all those movies and mp3s!']
  ONEHUNDRED = ['buy an upgrade of ram for your computer', 'buy a weeks worth of groceries' ]
  FIFTY = ['buy a new video game', 'get an oil change', 'treat a friend to some thai food', 'treat yourself to some sushi', 'buy a tank of gas' ]
  FORTY = [ 'go to a really nice resturant', 'treat a friend to some takeout', 'go to a concert']
  THIRTY = ['treat a friend to some takeout', 'buy a friend some flowers']
  TWENTY = ['take a friend out to a movie', 'order some pizzas', 'buy a new dvd']
  TEN = ['buy a sixpack', 'go to a movie', 'buy a new album', 'buy a new dvd', 'take yourself out to lunch' ]
  FIVE = ['purchase a tasty sub sandwich', 'take yourself out to lunch']
  THREE = ['buy a pack of potato chips', 'buy a bottle of wine', 'buy a breakfast bar']
  TWO = ['buy yourself some candy', 'purchase an ice cream bar',  'buy a protein bar']
  ONE = ['purchase a tasty beverage', 'buy an ice cream bar']
  ZERO = ['leave some change on the counter for a rainy day']

  AMOUNTS = {500 => FIVEHUNDRED, 300 => THREEHUNDRED, 200 => TWOHUNDRED, 100 => ONEHUNDRED, 50 => FIFTY, 40 => FORTY, 30 => THIRTY, 20 => TWENTY, 10 => TEN, 5 => FIVE, 3 => THREE, 2 => TWO, 1 => ONE, 0 => ZERO}

  def saved_comp
    saved = self.msrp - self.price
    pick = ZERO
    ar_pick = 0
    am = AMOUNTS.sort.reverse
    am.each do |key, val|
      if saved >= key
        ar_pick = val
      end
      break if saved >= key
    end
    size = ar_pick.size
    pick = rand(size)
    return ar_pick[pick]
  end

  def price
    my_price = self.reseller_price
    if my_price > 500
      if self.ds_vendor_type == 'IngramMicroProduct'
        my_price = ((self.reseller_price * 1.05) + 3.3).ceil - 0.01
      else
        my_price = ((self.reseller_price * 1.05) + 0.3).ceil - 0.01
      end
    else
      if self.ds_vendor_type == 'IngramMicroProduct'
        my_price = ((self.reseller_price * 1.08) + 10.3).ceil - 0.01
      else
        my_price = ((self.reseller_price * 1.08) + 0.3).ceil - 0.01
      end
    end
    if my_price < self.map
      return self.map
    end
    return my_price
  end

  def old_price
    my_price = ((self.reseller_price * 1.05) + 0.3).ceil - 0.01 
    if my_price < self.map
      return self.map
    end
    return my_price
  end

  def staggered_price
    my_price = self.reseller_price
    if my_price > 14000     #700
      my_price *= 1.05
    elsif my_price > 13000  #790
      my_price *= 1.06
    elsif my_price > 12000  #840
      my_price *= 1.07
    elsif my_price > 11000  #880
      my_price *= 1.08
    elsif my_price > 10000  #900 
      my_price *= 1.09
    elsif my_price > 9000   #900
      my_price *= 1.10
    elsif my_price > 8000   #960
      my_price *= 1.12
    elsif my_price > 7000   #980
      my_price *= 1.14
    elsif my_price > 6000   #960
      my_price *= 1.16
    elsif my_price > 5000   #900
      my_price *= 1.18
    elsif my_price > 4000   #760
      my_price *= 1.19
    elsif my_price > 3000   #600
      my_price *= 1.2
    elsif my_price > 70    #140
      my_price *= 1.2
    elsif my_price > 50     #17.5
      my_price *= 1.3
    elsif my_price > 10     #10
      my_price *= 1.40 
    elsif my_price <= 10    #2.50
      my_price *= 1.5
    end
    if self.msrp < my_price
      my_price = self.msrp - (0.1 * self.msrp)
    end
    return self.map if my_price < self.map
    return my_price
  end

  def remote_id
    if self.ds_vendor_type == 'DsdiProduct'
      return self.ds_vendor.model
    else
      return ''
    end
  end
  #before_create :create_slug
  #def create_slug
  #  self.slug = self.title.parameterize
  #end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  before_filter :login_required, :admin_login_required

  def index
  end

  def edit
    @product = Product.find(params[:id], :include => [:ds_vendor, :product_images])
    @product_image = @product.product_image
    @breadcrumb = @product.category.breadcrumb
    @related_products = Product.find(:all, :conditions => [ 'products.manufacturer = ? and products.id != ?', @product.manufacturer, @product.id], :limit => 4, :include => [:product_image,:product_images]) 
  end

  def update
    @product = Product.find(params[:id], :include => [:ds_vendor, :product_image, :product_images])
    @product_image = @product.product_image
    if @product.update_attributes(params[:product])
      if params[:product_image]
        puts 'in cont: product_image'
        @product_image = ProductImage.new(params[:product_image])
        puts 'in cont: product_image new'
        @product_image.product = @product
        if @product_image.save
          redirect_to product_path(@product) and return
        else
          puts 'errors in product image save'
        end
      end
    end
    flash[:notice] = "There was a problem"
    @breadcrumb = @product.category.breadcrumb
    @related_products = Product.find(:all, :conditions => [ 'products.manufacturer = ? and products.id != ?', @product.manufacturer, @product.id], :limit => 4, :include => :product_images) 
    render :action => 'edit'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def feed
    @products = Rails.cache.fetch( 'products_feed') do
      Product.find(:all, :limit => 10)
    end
    respond_to do |format|
      format.rss  { render :layout => false }
      format.xml { render 'feed.rss', :layout => false}
    end
  end

  # GET /products
  # GET /products.xml
  def index
    page = params[:page] || 1
    @featured_products = Rails.cache.fetch('featured_prod_8') do
      Product.all.where('category_id = 272').includes(:product_images).order('msrp ASC').limit(8)
    end
    @new_products = Rails.cache.fetch( 'new_prod_8') do
      Product.all.includes(:product_images).order('created_at DESC').limit(8)
    end
    @top_sellers = Rails.cache.fetch( 'top_seller_8' ) do
      Product.all.where('category_id in (564, 567)').includes(:product_images).order('msrp, created_at DESC').limit(8)
    end
    @recommended = Rails.cache.fetch( 'recommended_8' ) do
      Product.all.where('category_id = 274').includes(:product_images).order('msrp, created_at DESC').limit(8)
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
    end
  end
  
  def featured
    @section_title = "FEATURED PRODUCTS"
    page = params[:page] || 1
    @products = Rails.cache.fetch( 'featured_prod_pg_' + page.to_s ) do
      Product.where('category_id = 272').order('msrp ASC').includes(:product_images).paginate(:page => page)
    end
  end

  def new
    @section_title = "NEWEST PRODUCTS"
    page = params[:page] || 1
    @products = Rails.cache.fetch( 'newest_prod_pg_' + page.to_s) do
      Product.all.order('created_at DESC').includes(:product_images).paginate(:page => page)
    end
    render :featured
  end

  def top_sellers
    @section_title = "TOP SELLERS"
    page = params[:page] || 1
    @products = Rails.cache.fetch( 'top_prod_pg_' + page.to_s ) do
      Product.where('category_id in (564, 567)').order('msrp ASC').includes(:product_images).paginate(:page => page)
    end
    render :featured
  end

  def recommended
    @section_title = "RECOMMENDED PRODUCTS"
    page = params[:page] || 1
    @products = Rails.cache.fetch( 'rec_prod_pg_' + page.to_s ) do
      Product.where('category_id = 274').order('msrp, created_at DESC').includes(:product_images).paginate(:page => page)
    end
    render :featured
  end
  # GET /products/1
  # GET /products/1.xml
  def show
    @product = Product.where(:id => params[:id]).includes(:ds_vendor, :product_images, :category).first
      puts 'product is ' + @product.title.to_s
      puts 'category is ' + @product.category.to_s
      Rails.cache.fetch( 'product_' + params[:id].to_s + '_breadcrumb') do
        @breadcrumb = @product.category.breadcrumb
      end
    @related_products = Product.all.where( [ 'products.manufacturer = ? and products.id != ?', @product.manufacturer, @product.id]).includes(:product_images).limit(4)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/new
  # GET /products/new.xml
=begin
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product }
    end
  end
=end

  # GET /products/1/edit
=begin
  def edit
    @product = Product.find(params[:id])
  end
=end

  # POST /products
  # POST /products.xml
=begin
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to(@product, :notice => 'Product was successfully created.') }
        format.xml  { render :xml => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end
=end

  # PUT /products/1
  # PUT /products/1.xml
=begin
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to(@product, :notice => 'Product was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end
=end

  # DELETE /products/1
  # DELETE /products/1.xml
=begin
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(products_url) }
      format.xml  { head :ok }
    end
  end
=end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= form_for(@product) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :sku %><br />
    <%= f.text_field :sku %>
  </p>
  <p>
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </p>
  <p>
    <%= f.label :manufacturer %><br />
    <%= f.text_field :manufacturer %>
  </p>
  <p>
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </p>
  <p>
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity %>
  </p>
  <p>
    <%= f.label :reseller_price %><br />
    <%= f.text_field :reseller_price %>
  </p>
  <p>
    <%= f.label :msrp %><br />
    <%= f.text_field :msrp %>
  </p>
  <p>
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </p>
  <p>
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/featured.html.erb
<% content_for :page_stylesheet do -%>
  <%= stylesheet_link_tag 'multi-prod' %>
<% end %>
<% content_for :page_title do -%>
  <%= @section_title %>
<% end %>
<div class="section"><%= @section_title %></div>
<%= render :partial => 'locals/products', :locals => {:products => @products } %>
<div id="page_links">
  <%= will_paginate %>
</div>

app/views/products/index.html.erb
<% content_for :page_stylesheet do -%>
  <%= stylesheet_link_tag 'multi-prod' %>
<% end %>
<% content_for :page_title do -%>
  Featured Products, Top Sellers, Recommended, and New items
<% end %>
<% content_for :page_meta do -%>
  <meta name="title" content="dreambop.com: Excellent new products and unbeatable service" />
  <meta name="description" content="dreambop.com: Excellent new products and unbeatable service" />
  <meta name="keywords" content="fantastic online experience with superior information in an enjoyable way." />
<% end %>
<div class="section">FEATURED PRODUCTS</div>
<%= render :partial => 'locals/products', :locals => {:products => @featured_products} %>
<div class="section-footer">
  <%= link_to 'See more featured products . . .', featured_path %>
</div>

<div class="section">TOP SELLERS</div>
<%= render :partial => 'locals/products', :locals => {:products => @top_sellers } %>
<div class="section-footer">
  <%= link_to 'See more top sellers . . .', top_sellers_path %>
</div>

<div class="section">RECOMMENDED</div>
<%= render :partial => 'locals/products', :locals => {:products => @recommended } %>
<div class="section-footer">
  <%= link_to 'See more recommended products . . .', recommended_path %>
</div>

<div class="section">NEW PRODUCTS</div>
<%= render :partial => 'locals/products', :locals => {:products => @new_products} %>
<div class="section-footer">
  <%= link_to 'See more new products . . .', new_path %>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= form_for(@product) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :sku %><br />
    <%= f.text_field :sku %>
  </p>
  <p>
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </p>
  <p>
    <%= f.label :manufacturer %><br />
    <%= f.text_field :manufacturer %>
  </p>
  <p>
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </p>
  <p>
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity %>
  </p>
  <p>
    <%= f.label :reseller_price %><br />
    <%= f.text_field :reseller_price %>
  </p>
  <p>
    <%= f.label :msrp %><br />
    <%= f.text_field :msrp %>
  </p>
  <p>
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </p>
  <p>
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% content_for :page_stylesheet do -%>
  <%= stylesheet_link_tag 'product', 'categories', 'multi-prod' %>
<% end %>

<% content_for :page_js do-%>
<script type="text/javascript">
        $(document).ready(function(){ 
          $('#saved').click( function() { jqDialog.notify("You could <%= @product.saved_comp %> for that.", 3); return false; } );
          FB.Event.subscribe('edge.create', function(response) {
            //alert('page liked');
            // do something with response.session
          });
          FB.Event.subscribe('comments.add', function(response) {
            //alert('page liked');
            // do something with response.session
          });
        });
        $(window).load(function(){ 
        });
</script>
<% end %>

<% content_for :page_title do -%>
  <%= @product.title %> : <%= number_to_currency(@product.price) %>
<% end %>

<% content_for :page_meta do -%>
  <meta name="title" content="dreambop.com: <%= @product.title %>: <%= @product.category.display_name %>" />
  <meta name="description" content="dreambop.com: <%= @product.category.display_name %> - <%= @product.description.gsub(%r{</?[^>]+?>}, '').gsub(/"/, '') %>" />
  <meta name="keywords" content="<%= @product.title.to_s + ', ' + @product.manufacturer.to_s + ', ' + @product.description.gsub(%r{</?[^>]+?>}, '').gsub(/"/, '') %>" />
  <!-- facebook page stuff -->
  <meta property="og:title" content="<%= @product.title %>"/> 
  <meta property="og:type" content="product"/> 
  <meta property="og:image" content="<%= @product.image %>"/> 
  <meta property="og:url" content="<%= product_url(@product) %>"/> 
  <meta property="og:site_name" content="dreambop"/> 
  <meta property="fb:admins" content="3614966"/>
  <meta property="og:description" content="<%= @product.description.gsub(%r{</?[^>]+?>}, '').gsub(/"/, '') %>"/>
<% end %>

<div id="breadcrumb">
  <%= render :partial => 'locals/breadcrumb', :locals => { :breadcrumb => @breadcrumb } %>
</div>
<% if current_user and current_user.has_role?('admin') %>
  <div id="aedit">
      <%= link_to 'Edit this product', edit_admin_product_path(@product) %>
  </div>
<% end %>
<div class="section">PRODUCT DESCRIPTION</div>
<div id="picture">
   <%= link_to(image_tag(@product.image(300), :style => 'max-width: 300px'), @product.image) %></td>
</div>
<div id="description">
  <span class=""><b><%=h @product.title %></b></span>
  <br/>
  <span id="description-text" class=""><%= raw @product.description %></span>
</div>
<div class="clear"></div>
<div id="price">
  <div id="price-text"><%= number_to_currency(@product.price) %></div>
  <div id="condition">Condition: New</div>
  <% if @product.not_na? %>
  <div class="supporting_info">In stock: <%= @product.display_availability %></div>
  <% end %>
  <% np = @product.msrp
     if np <= 0 
       np = "N/A"
     else
       np = number_to_currency(np)
     end %>
  <div class="supporting_info">Normal Price: <%= np %> </div>
  <% saved = @product.msrp - @product.price %>
  <% if saved > 0 %>
  <div class="supporting_info">You save: <a href='#' id="saved"><%= number_to_currency(@product.msrp - @product.price) %></a></div>
  <% end %>
  <div id="fb_like_btn">
     <script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like font="verdana" ref="<%= @product.id.to_s %>" href="<%= product_url(@product) %>" show_faces="true" width="200"></fb:like>
  </div>
  <div id="about_fb_like">
    Like this page and get money off your purchase. Read more about <%= link_to 'the dreambop facebook coupon', :action => 'facebook_coupon', :controller => 'about' %>
  </div>
  <div id="add-to-cart">
    <%= form_for @product, :url => { :action => :update, :controller => :cart, :id => @product }, :method => :patch do |f| %>
      <%= submit_tag 'Add to cart', :src => '/images/button_add_to_cart.jpg', :type => 'image' %> 
    <% end %>
   </div>
</div>
<br/>
<br/>
<div class="clear"></div>
<div class="section">DETAILS</div>
<div id="details">
  <% ds_prod = @product.ds_vendor %>
  <% if ds_prod.class == DandhProduct %>
  <p>
    <b>MANUFACTURER URL</b>
    <%= link_to ds_prod.manufacturer_url, 'http://' + ds_prod.manufacturer_url, :target => '_blank' %>
  </p>
  <p>
    <b>WARRANTY LENGTH</b>
    <%=h ds_prod.warranty_length %>
  </p>
  <p>
    <b>OTHER TECH DETAILS</b>
    <br/><%= raw ds_prod.tech_description %>
  </p>
  <% end %>
  <p>
    <a href="/manufacturers"><b>MANUFACTURER</b>:</a>
    <%= link_to @product.manufacturer, :action => :show, :controller => :manufacturers, :id => @product.manufacturer.gsub(/ /, '+') %>
  </p>

  <p>
    <b>WEIGHT:</b>
    <%=h @product.weight %> lb(s).
  </p>
</div>
<div class="padprod"></div>
<div class="section">RELATED PRODUCTS</div>
<%= render :partial => 'locals/products', :locals => {:products => @related_products} %>
<div class="section-footer">
  <%= link_to 'See more related products . . .', :action => :show, :controller => :manufacturers, :id => @product.manufacturer.gsub(/ /, '+') %>
</div>